### ISSUE TITLE
lazyload启动失败

### ISSUE THREAD

**Issue by xiangtianyu** [slime-io/slime#109]
启用lazyload时在应用namespace下的global sidecar启动失败，日志如下：
2021-11-04T06:00:31.056838Z     error   failed to start envoy agent: failed to generate bootstrap metadata: failed to find root CA cert for XDS: root CA file for XDS does not exist var/run/secrets/istio/root-cert.pem
Error: failed to start envoy agent: failed to generate bootstrap metadata: failed to find root CA cert for XDS: root CA file for XDS does not exist var/run/secrets/istio/root-cert.pem

lazyload.yaml
```yaml
---
apiVersion: config.netease.com/v1alpha1
kind: SlimeBoot
metadata:
  name: lazyload
  namespace: mesh-operator
spec:
  image:
    pullPolicy: Always
    repository: docker.io/slimeio/slime-lazyload
    tag: v0.2.6-d808438
  module:
    - name: lazyload
      enable: true
      fence:
        wormholePort:
          - "9080"
      metric:
        prometheus:
          address: http://prometheus.istio-system:9090
          handlers:
            destination:
              query: |
                sum(istio_requests_total{source_app="$source_app",reporter="destination"})by(destination_service)
              type: Group
  component:
    globalSidecar:
      enable: true
      type: namespaced
      namespace:
        - istio-public
      resources:
        requests:
          cpu: 200m
          memory: 200Mi
        limits:
          cpu: 400m
          memory: 200Mi
      image:
        repository: istio/proxyv2
        tag: 1.11.4
    pilot:
      enable: true
      resources:
        requests:
          cpu: 200m
          memory: 200Mi
        limits:
          cpu: 400m
          memory: 800Mi
      image:
        repository: docker.io/slimeio/pilot
        tag: globalPilot-7.0-v0.0.3-713c611962

```

[ X ] Configuration Lazy Loading
[ ] Http Plugin Management
[ ] Adaptive Ratelimit
[ ] Slime Boot
