### ISSUE TITLE
configsource should not specified in slimeboot cr if not use

### ISSUE THREAD

**Issue by MouceL** [slime-io/slime#245]
**whatever you want to say to slime developers**

configsource should not specified in slimeboot cr if not use

```yaml
apiVersion: config.netease.com/v1alpha1
kind: SlimeBoot
metadata:
  name: limiter
  namespace: mesh-operator
spec:
  image:
    pullPolicy: Always
    repository: docker.io/slimeio/slime-limiter
    tag: v0.5.0_linux_amd64
  module:
    - name: limiter
      kind: limiter
      enable: true
      general:
        disableGlobalRateLimit: true
        disableAdaptive: true
        disableInsertGlobalRateLimit: true
      global:
        log:
          logLevel: info
        configSources:
          - address: ss:// 
```
we use `ss://`  to skip init k8s for default

```go
	if len(config.Global.ConfigSources) > 0 {
		for _, configSource := range config.Global.ConfigSources {
			if strings.HasPrefix(configSource.Address, McpOverXdsConfigSourcePrefix) {
				if mc, err := initXdsMonitorController(configSource); err != nil {
					return nil, err
				} else {
					mcs = append(mcs, mc)
				}
				continue
			}
			if strings.HasPrefix(configSource.Address, KubernetesConfigSourcePrefix) {
				if mc, err := initK8sMonitorController(configSource); err != nil {
					return nil, err
				} else {
					mcs = append(mcs, mc)
				}
				continue
			}
		}
	} else {
		// init k8s for default
		if mc, err := initK8sMonitorController(nil); err != nil {
			return nil, err
		} else {
			mcs = append(mcs, mc)
		}
	}
```
