### ISSUE TITLE
服务/接口级别限流

### ISSUE THREAD

**Issue by qinggniq** [slime-io/slime#25]
**whatever you want to say to slime developers**
目前slime似乎只针对被调用方单机进行局部限流，有没有计划支持接口级别的全局/单机限流？

**Comment by ydh926** [comment]
我们目前并没有考虑将限流放在调用方，如果你希望在调用方实现全局/单机限流可以考虑通过plugin模块进行配置,如下：
```yaml
apiVersion: microservice.slime.io/v1alpha1
kind: PluginManager
metadata:
  name: my-plugin
  namespace: default
spec:
  plugins:
  - enable: true          # 插件开关
    name: envoy.filters.http.local_ratelimit     # 插件名称
---
apiVersion: microservice.slime.io/v1alpha1
kind: EnvoyPlugin
metadata:
  name: limiter
  namespace: default
spec:
  route:
  - istio.com/abc # host/name in virtualservice
  plugins:
  - name: envoy.filters.http.local_ratelimit
    inline:
      settings:
      # your settings
```
