### ISSUE TITLE
明确限流的Match语义

### ISSUE THREAD

**Issue by MouceL** [slime-io/slime#282]
**whatever you want to say to slime developers**

目前Match将header限流和query限流混合在一起，语义不明确，计划将其拆分

```yaml
spec:
  sets:
    _base:
      descriptor:
      - action:
          fill_interval:
            seconds: 10
          quota: "2"
          strategy: "single"
        condition: "true"
        target:
          port: 9080
        matchRequest:
          headers:
          - name: key1
            exact_match: value1
          - name: key2
            exact_match: value2
          queryParams:
          - name: key3
            exact_match: value3
```
