### ISSUE TITLE
不支持External Control Plane方案架构

### ISSUE THREAD

**Issue by dryheartGo** [slime-io/slime#319]
**使用External Control Plane方案部署Istio，limiter组件不支持**

- Slime version: 0.6.0
- Istio version: 1.13.2
- k8s version: 1.21.10

[ ] Configuration Lazy Loading
[ ] Http Plugin Management
[X] Adaptive Ratelimit
[ ] Slime Boot

limiter log：
```
time=2023-03-16T09:54:26Z level=info msg=get err in queryServicePods, get service namespace/xxx-service faild, services "xxx-service" not found module=limiter pkg=controllers
```
感觉是limiter使用了k8s api，无法找到remote cluster的CR信息

**Comment by cywang1905** [comment]
目前 Slime 支持多主的多集群场景，每套集群单独部署一套 Slime ，只管理本集群。

主从架构的多集群场景我们没有验证过，可以尝试通过配置 `configSource` 字段，指定多个 apiserver 地址来实现。一个例子如下
```yaml
# slimeboot cr
apiVersion: config.netease.com/v1alpha1
kind: SlimeBoot
metadata:
  name: limiter
  namespace: mesh-operator
spec:
  image:
    pullPolicy: Always
    repository: docker.io/slimeio/slime-limiter
    tag: v0.6.0_linux_amd64
  module:
    - name: limiter
      kind: limiter
      enable: true
      general:
        disableGlobalRateLimit: true
        disableAdaptive: true
        disableInsertGlobalRateLimit: true
      global:
        log:
          logLevel: info
        configSources:
          - address: k8s://xxx
          - address: k8s://xxx 
```
