### ISSUE TITLE
Proposal: Lazyload use envoy as a global sidecar for supporting multi protocol

### ISSUE THREAD

**Issue by Patrick0308** [slime-io/slime#373]
**影响的子模块(在下面列表中打'X')**

- [X] 配置懒加载
- [ ] 插件管理
- [ ] 智能限流
- [ ] 注册仓库
- [ ] 安装Boot

**问题背景**
lazy load not support grpc
**您的提案内容**

 Using envoy as global sidecar because its pluginability and updating configuration dynamically. 

## Architecture
![image](https://github.com/slime-io/slime/assets/5486149/d3daa3d3-5375-41c5-8115-a1970c6a0fb1)

## H1/H2 
envoy configuration example:
```
static_resources:
  listeners:
  - address:
      socket_address:
        address: 0.0.0.0
        port_value: 20000
    filter_chains:
    - filters:
      - name: envoy.filters.network.http_connection_manager
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
          access_log:
          - name: envoy.access_loggers.stdout
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.access_loggers.stream.v3.StdoutAccessLog
          codec_type: AUTO
          stat_prefix: health 
          use_remote_address: true
          route_config:
            name: health 
            virtual_hosts:
            - name: all
              domains:
              - "*"
              routes:
              - match:
                  prefix: "/"
                direct_response:
                  status: 200
                  body:
                    inline_string: "success"
          http_filters:
          - name: envoy.filters.http.router
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.filters.http.router.v3.Router
  - address:
      socket_address:
        address: 0.0.0.0
        port_value: 80
    filter_chains:
    - filters:
      - name: envoy.filters.network.http_connection_manager
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
          codec_type: AUTO
          access_log:
          - name: envoy.access_loggers.stdout
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.access_loggers.stream.v3.StdoutAccessLog
          stat_prefix: egress_http
          common_http_protocol_options:
            idle_timeout: 840s
          use_remote_address: true
          route_config:
            name: proxy 
            virtual_hosts:
            - name: all
              domains:
              - "*"
              routes:
              - match:
                  prefix: "/"
                route:
                  cluster: original_dst_cluster 
          http_filters:
          - name: envoy.filters.http.router
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.filters.http.router.v3.Router
  clusters:
  - cleanupInterval: 8640000s
    connectTimeout: 10s
    lbPolicy: CLUSTER_PROVIDED
    name: original_dst_cluster 
    type: ORIGINAL_DST
    original_dst_lb_config:
      use_http_header: true
      http_header_name: "Slime-Orig-Dest"
    typedExtensionProtocolOptions:
      envoy.extensions.upstreams.http.v3.HttpProtocolOptions:
        '@type': type.googleapis.com/envoy.extensions.upstreams.http.v3.HttpProtocolOptions
        useDownstreamProtocolConfig:
          http2ProtocolOptions:
            maxConcurrentStreams: 1073741824
          httpProtocolOptions: {}
```

## h1/h2 On Same Svc's Same Port
Now global sidecar svc port protocol is http. Istio inbound sidecar will downgrade http2 to http1. This a way to support it. 
Configure:
```
apiVersion: v1
kind: Service
metadata:
  annotations:
    meta.helm.sh/release-name: lazyload
    meta.helm.sh/release-namespace: mesh-operator
  labels:
    app: global-sidecar
    app.kubernetes.io/managed-by: Helm
    service: global-sidecar
  name: global-sidecar
  namespace: mesh-operator
spec:
  ports:
  - name: http2-80
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: global-sidecar
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
---
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: global-sidecar
  namespace: mesh-operator
spec:
  host: global-sidecar.mesh-operator.svc.cluster.local
  trafficPolicy:
    connectionPool:
      http:
        useClientProtocol: true
```

## Other protocol 
Lazyload create svc for each other protocol and update to-global-sidecar envoy filter.

**Comment by YonkaFang** [comment]
感谢。 grpc的支持确实是比较关注的点。

请问有没有相关信息能提供一下，比如用于验证功能的grpc（consumer、provider）demo、global sidecar 镜像 等？

**Comment by Patrick0308** [comment]
@YonkaFang 
global sidecar 镜像：https://hub.docker.com/r/patrick0308/slime-envoy
grpc demo: https://github.com/h3poteto/istio-grpc-example

**Comment by MouceL** [comment]
用envoy替代global-sidecar需要注意以下几点

1. 目前没有纳管http外的port

这就导致如果grpc server 50051 listener未下发，grpc client请求根本走不到兜底逻辑，所以需要将portName以http/http2/grpc开头的端口都纳管进来。- TODO

2. 共用80端口问题 

grpc请求兜底到 outbound|80||global-sidecar.mesh-operator.svc.cluster.local

http1.1请求也被兜底到80 outbound|80||global-sidecar.mesh-operator.svc.cluster.local

- 如果global-sidecar端口写成http

```
  - name: http-80
    port: 80
    protocol: TCP
    targetPort: 80
```

那么http1.1请求可以正常转发，而grpc请求在global-sidecar中会被降级成http1.1

- 如果global-sidecar端口写成http2

```
  - name: http2-80
    port: 80
    protocol: TCP
    targetPort: 80
```
那么grpc请求可以正常转发，而http1.1请求会被升级成http2.0

为了解决这个问题，我们需要指定 `useClientProtocol：true`

```
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: global-sidecar
  namespace: mesh-operator
spec:
  host: global-sidecar.mesh-operator.svc.cluster.local
  trafficPolicy:
    connectionPool:
      http:
        useClientProtocol: true
```

最后形态是指定global-sidecar的80端口为http2 + 下发`useClientProtocol：true`

这样，grpc请求正常由于指定了http2而正常转发，http1.1请求也会因为指定了`useClientProtocol：true`而安装客户端协议转发

3. 目前还存在一个问题

短域名请求，在global-sidecar转发中，只能走passthrough
