### ISSUE TITLE
lazyload should support smartdns 

### ISSUE THREAD

**Issue by Patrick0308** [slime-io/slime#385]
**问题背景**

场景一：
在多集群环境中，当要被调用的服务不在本集群中，如果不开启 smart dns，请求调用时会解析 host 失败。

场景二：
istio serviceentries 也是依赖 smart dns 解析的 host

**您想要的解决方案**

在集群中有一个 dns 辅助服务器, 并添加到默认的 /etc/resolv.conf 中。

原本的 /etc/resolv.conf :
```
nameserver 172.20.0.10
search core.svc.cluster.local svc.cluster.local cluster.local vpc.internal ap-east-1.compute.internal
options ndots:5
```
假如 dns 服务的 cluster ip 是 172.20.0.11， 新的 /etc/resolv.conf :
```
nameserver 172.20.0.10 
nameserver 172.20.0.11
search core.svc.cluster.local svc.cluster.local cluster.local vpc.internal ap-east-1.compute.internal
options ndots:5
```

**您考虑过的替代方案**

一个全局的 dns 代理，这个方案风险过高

**额外的上下文**

**Comment by MouceL** [comment]
关于场景二: 

解析出来的那个ip是不是真的并不重要，只要能转发到gs，就能流程走通

所以我们修改了内部的pilotagent，if xx then mock ..

这个做法不够普遍..

**Comment by Patrick0308** [comment]
@MouceL 两个场景解析出来的 ip 是什么都不太重要，只要 dns 正常就行。

**Comment by Patrick0308** [comment]
想到一种更加简单的方案，初步想法是自动同步不在这个集群的 k8s svc 至本集群。

方案：
1. lazyload 使用 xds 协议监听 istiod 的 cds，eds 协议。
2. 当 eds 中都不是本集群的节点（通过 ip 段判断？），并且 cds 符合 svc 资源特征 ，自动同步至没有 workload 的 service entries 中。

```
apiVersion: networking.istio.io/v1beta1
kind: ServiceEntry
metadata:
  name: lazyload-serviceentries
  namespace: skopos-pre
spec:
  hosts:
  - test.default.svc.cluster.local
  - test1.default.svc.clsuter.local
  location: MESH_INTERNAL
  ports:
  - name: grpc-8080
    number: 8080
    protocol: GRPC
  resolution: STATIC
```
