### ISSUE TITLE
【istio-1.16.5】serviceentry from meshregistry does not work with Istio virtualservice + destinationrule

### ISSUE THREAD

**Issue by tanjunchen** [slime-io/slime#408]
**问题描述**
- [X] question 1：There are some problem with the host in serviceentry  even though consumer-demo can access provider-demo through serviceentry. But the dr+vs strategy of the istio is not ok for consumer-demo. 
The dr+vs refer to https://github.com/tanjunchen/demo-registry2istio/tree/main/k8s. 
Related Issue: https://github.com/istio/istio/issues/45401.
The routing of vs+dr will be not ok for the serviceentry service(No FQDN) from meshregistry.
https://github.com/tanjunchen/demo-registry2istio/blob/main/k8s/demo-dr-vs.yaml

<img width="1434" alt="image" src="https://github.com/slime-io/slime/assets/19339970/f89fbbdb-cb07-4b96-8aa5-613245016410">

- [ ] question 2：the logs of meshregistry alway output.(Not Good).
```
2023-07-21T07:17:22.573225Z	info	mcp-xds	Pushed networking.istio.io/v1beta1/ProxyConfig to sidecar~10.0.0.78~istiod-558df7d7cd-jz8nl.istio-system~istio-system.svc.cluster.local-1 count=0 size=0 nonce=
2023-07-21T07:17:22.573229Z	info	mcp-xds	recv req security.istio.io/v1beta1/AuthorizationPolicy from sidecar~10.0.0.78~istiod-558df7d7cd-jz8nl.istio-system~istio-system.svc.cluster.local-1, err <nil>, nonce
2023-07-21T07:17:22.573243Z	info	mcp-xds	Pushed security.istio.io/v1beta1/AuthorizationPolicy to sidecar~10.0.0.78~istiod-558df7d7cd-jz8nl.istio-system~istio-system.svc.cluster.local-1 count=0 size=0 nonce=
2023-07-21T07:17:22.573258Z	info	mcp-xds	recv req security.istio.io/v1beta1/PeerAuthentication from sidecar~10.0.0.78~istiod-558df7d7cd-jz8nl.istio-system~istio-system.svc.cluster.local-1, err <nil>, nonce
2023-07-21T07:17:22.573275Z	info	mcp-xds	Pushed security.istio.io/v1beta1/PeerAuthentication to sidecar~10.0.0.78~istiod-558df7d7cd-jz8nl.istio-system~istio-system.svc.cluster.local-1 count=0 size=0 nonce=
2023-07-21T07:17:22.573481Z	info	mcp-xds	recv req security.istio.io/v1beta1/RequestAuthentication from sidecar~10.0.0.78~istiod-558df7d7cd-jz8nl.istio-system~istio-system.svc.cluster.local-1, err <nil>, nonce
2023-07-21T07:17:22.573559Z	info	mcp-xds	Pushed security.istio.io/v1beta1/RequestAuthentication to sidecar~10.0.0.78~istiod-558df7d7cd-jz8nl.istio-system~istio-system.svc.cluster.local-1 count=0 size=0 nonce=
2023-07-21T07:17:22.573566Z	info	mcp-xds	recv req telemetry.istio.io/v1alpha1/Telemetry from sidecar~10.0.0.78~istiod-558df7d7cd-jz8nl.istio-system~istio-system.svc.cluster.local-1, err <nil>, nonce
2023-07-21T07:17:22.573595Z	info	mcp-xds	Pushed telemetry.istio.io/v1alpha1/Telemetry to sidecar~10.0.0.78~istiod-558df7d7cd-jz8nl.istio-system~istio-system.svc.cluster.local-1 count=0 size=0 nonce=
2023-07-21T07:17:22.573600Z	info	mcp-xds	recv req core/v1alpha1/MeshConfig from sidecar~10.0.0.78~istiod-558df7d7cd-jz8nl.istio-system~istio-system.svc.cluster.local-1, err <nil>, nonce
2023-07-21T07:17:22.573644Z	info	mcp-xds	Pushed core/v1alpha1/MeshConfig to sidecar~10.0.0.78~istiod-558df7d7cd-jz8nl.istio-system~istio-system.svc.cluster.local-1 count=0 size=0 nonce=
2023-07-21T07:17:22.573650Z	info	mcp-xds	recv req extensions.istio.io/v1alpha1/WasmPlugin from sidecar~10.0.0.78~istiod-558df7d7cd-jz8nl.istio-system~istio-system.svc.cluster.local-1, err <nil>, nonce
```

**影响的子模块(在下面列表中打'X')**

- [ ] 配置懒加载
- [ ] 插件管理
- [ ] 智能限流
- [X] 注册仓库
- [ ] 安装Boot

**重现问题的步骤**

the source refer to https://github.com/tanjunchen/demo-registry2istio/tree/main/k8s

1. install meshregistry component according to https://slime-io.github.io/user-guide/meshregistry/tutorial/
I use the new image from this pr https://github.com/slime-io/slime/pull/405
```
apiVersion: config.netease.com/v1alpha1
kind: SlimeBoot
metadata:
  name: meshregistry
  namespace: mesh-operator
spec:
  image:
    pullPolicy: Always
    repository: registry.baidubce.com/csm/slime-meshregistry
    tag: fix-bug-841427a_linux_amd64-dirty_bcdc6b5
    #repository: docker.io/slimeio/slime-meshregistry
    #tag: v0.8.0
  module:
    - name: meshregistry
      kind: meshregistry
      enable: true
      general:
        LEGACY:
          NacosSource:
            Enabled: true
            RefreshPeriod: 30s
            Address:
              - "http://nacos:8848"
            Mode: polling
```
2. install istio (1.16.5) , the istio iop yaml:
```
https://github.com/tanjunchen/demo-registry2istio/blob/main/k8s/istio-config.yaml
```
3. install nacos 
```
https://github.com/tanjunchen/demo-registry2istio/blob/main/k8s/nacos.yaml
```
4. deploy consumer-demo and provider-demo, the yaml：
```
https://github.com/tanjunchen/demo-registry2istio/blob/main/k8s/demo.yaml
```
5. the xdsCache from meshregistry:  http://localhost:8081/meshregistry/xdsCache
```
{
  "networking.istio.io/v1alpha3/ServiceEntry": [
    {
      "type": "networking.istio.io/v1alpha3/ServiceEntry",
      "name": "consumer-demo",
      "namespace": "nacos",
      "labels": {
        "app": "consumer-demo",
        "registry": "nacos"
      },
      "annotations": {
        "ResourceVersion": "2023-07-21 06:18:25.025222868 +0000 UTC m=+35.665133534"
      },
      "creationTimestamp": "2023-07-21T06:18:25.025197428Z",
      "Spec": {
        "hosts": [
          "consumer-demo"
        ],
        "addresses": [],
        "ports": [
          {
            "number": 80,
            "protocol": "HTTP",
            "name": "http-80"
          },
          {
            "number": 9999,
            "protocol": "HTTP",
            "name": "http-9999"
          }
        ],
        "resolution": "STATIC",
        "endpoints": [
          {
            "address": "10.0.1.249",
            "ports": {
              "http-80": 9999,
              "http-9999": 9999
            },
            "labels": {
              "app": "consumer-demo",
              "istio-locality": "gz.zoneC",
              "pod-template-hash": "6478988b9b",
              "preserved.register.source": "SPRING_CLOUD",
              "security.istio.io/tlsMode": "istio",
              "service.istio.io/canonical-name": "consumer-demo",
              "service.istio.io/canonical-revision": "latest"
            },
            "locality": "gz/zoneC"
          }
        ]
      }
    },
    {
      "type": "networking.istio.io/v1alpha3/ServiceEntry",
      "name": "provider-demo",
      "namespace": "nacos",
      "labels": {
        "app": "provider-demo",
        "registry": "nacos"
      },
      "annotations": {
        "ResourceVersion": "2023-07-21 06:18:25.025246355 +0000 UTC m=+35.665157019"
      },
      "creationTimestamp": "2023-07-21T06:18:25.025236384Z",
      "Spec": {
        "hosts": [
          "provider-demo"
        ],
        "addresses": [],
        "ports": [
          {
            "number": 80,
            "protocol": "HTTP",
            "name": "http-80"
          },
          {
            "number": 10001,
            "protocol": "HTTP",
            "name": "http-10001"
          }
        ],
        "resolution": "STATIC",
        "endpoints": [
          {
            "address": "10.0.0.77",
            "ports": {
              "http-10001": 10001,
              "http-80": 10001
            },
            "labels": {
              "app": "provider-demo",
              "istio-locality": "gz.zoneC",
              "pod-template-hash": "768db54778",
              "preserved.register.source": "SPRING_CLOUD",
              "security.istio.io/tlsMode": "istio",
              "service.istio.io/canonical-name": "provider-demo",
              "service.istio.io/canonical-revision": "v2",
              "version": "v2"
            },
            "locality": "gz/zoneC"
          },
          {
            "address": "10.0.1.250",
            "ports": {
              "http-10001": 10001,
              "http-80": 10001
            },
            "labels": {
              "app": "provider-demo",
              "istio-locality": "gz.zoneC",
              "pod-template-hash": "7dd55b7994",
              "preserved.register.source": "SPRING_CLOUD",
              "security.istio.io/tlsMode": "istio",
              "service.istio.io/canonical-name": "provider-demo",
              "service.istio.io/canonical-revision": "v1",
              "version": "v1"
            },
            "locality": "gz/zoneC"
          }
        ]
      }
    }
  ]
}
```
6. the configz of istiod, http://localhost:8080/debug/configz
```
{
	"kind": "ServiceEntry",
	"apiVersion": "networking.istio.io/v1alpha3",
	"metadata": {
		"name": "provider-demo",
		"namespace": "nacos",
		"resourceVersion": "2023-07-21 06:20:15.277115637 +0000 UTC m=+9186.965321822",
		"creationTimestamp": "2023-07-21T06:18:25Z",
		"labels": {
			"app": "provider-demo",
			"registry": "nacos"
		},
		"annotations": {
			"ResourceVersion": "2023-07-21 06:18:25.025246355 +0000 UTC m=+35.665157019"
		}
	},
	"spec": {
		"endpoints": [{
				"address": "10.0.0.77",
				"labels": {
					"app": "provider-demo",
					"istio-locality": "gz.zoneC",
					"pod-template-hash": "768db54778",
					"preserved.register.source": "SPRING_CLOUD",
					"security.istio.io/tlsMode": "istio",
					"service.istio.io/canonical-name": "provider-demo",
					"service.istio.io/canonical-revision": "v2",
					"version": "v2"
				},
				"locality": "gz/zoneC",
				"ports": {
					"http-10001": 10001,
					"http-80": 10001
				}
			},
			{
				"address": "10.0.1.250",
				"labels": {
					"app": "provider-demo",
					"istio-locality": "gz.zoneC",
					"pod-template-hash": "7dd55b7994",
					"preserved.register.source": "SPRING_CLOUD",
					"security.istio.io/tlsMode": "istio",
					"service.istio.io/canonical-name": "provider-demo",
					"service.istio.io/canonical-revision": "v1",
					"version": "v1"
				},
				"locality": "gz/zoneC",
				"ports": {
					"http-10001": 10001,
					"http-80": 10001
				}
			}
		],
		"hosts": [
			"provider-demo"
		],
		"ports": [{
				"name": "http-80",
				"number": 80,
				"protocol": "HTTP"
			},
			{
				"name": "http-10001",
				"number": 10001,
				"protocol": "HTTP"
			}
		],
		"resolution": "STATIC"
	}
}
```
7. the config_dump of consumer-demo
[configdump.tar.gz](https://github.com/slime-io/slime/files/12117623/configdump.tar.gz)

**Comment by MouceL** [comment]
if lazyload deployed in your local cluster

1. consumer cnofigdump is better than provider-demo

2. you should have looked at consumer's accesslog

**Comment by tanjunchen** [comment]
> 1. if lazyload deployed in your local cluster
> 
> more info ..
> 
> 2. consumer cnofigdump
> 3. attach accesslog in consumer's envoy

1. no lazyload
2. the config_dump of consumer
[configdump.tar.gz](https://github.com/slime-io/slime/files/12117626/configdump.tar.gz)
3. the log
```
kubectl -n nacos get pod -owide
NAME                                READY   STATUS    RESTARTS   AGE     IP           NODE           NOMINATED NODE   READINESS GATES
consumer-demo-6478988b9b-bggks      2/2     Running   0          3h56m   10.0.1.249   192.168.1.17   <none>           <none>
provider-demo-v1-7dd55b7994-vd2ww   2/2     Running   0          3h56m   10.0.1.250   192.168.1.17   <none>           <none>
provider-demo-v2-768db54778-f6t5l   2/2     Running   0          3h56m   10.0.0.77    192.168.1.12   <none>           <none>
 kubectl -n nacos  exec -it consumer-demo-6478988b9b-bggks  -c consumer-demo -- curl 10.0.1.249:9999/echo-rest/aaaaa
{"timestamp":"2023-07-21T07:38:44.387+0000","status":500,"error":"Internal Server Error","message":"I/O error on GET request for \"http://provider-demo/echo/aaaaa\": provider-demo; nested exception is java.net.UnknownHostException: provider-demo","path":"/echo-rest/aaaaa"}

the log from istio-proxy of consumer-demo is null.
``

**Comment by MouceL** [comment]
> kubectl -n nacos  exec -it consumer-demo-6478988b9b-bggks  -c consumer-demo

kubectl -n nacos  exec -it consumer-demo-6478988b9b-bggks  -c istio-proxy

**Comment by tanjunchen** [comment]
> > kubectl -n nacos  exec -it consumer-demo-6478988b9b-bggks  -c consumer-demo
> 
> kubectl -n nacos exec -it consumer-demo-6478988b9b-bggks -c istio-proxy

done.

**Comment by tanjunchen** [comment]
@MouceL  question 1 have been resolved.
It seems that we must use smart DNS. 
Smart DNS must add *ISTIO_META_DNS_AUTO_ALLOCATE=true* in proxyMetadata.
ok：
```
proxyMetadata:
  ISTIO_META_DNS_AUTO_ALLOCATE: "true"
  ISTIO_META_DNS_CAPTURE: "true"
```
fail：
```
proxyMetadata:
  ISTIO_META_DNS_CAPTURE: "true"
```

```
apiVersion: v1
data:
  mesh: |-
    accessLogFile: /dev/stdout
    accessLogFormat: |
      [%START_TIME%] %REQ(X-META-PROTOCOL-APPLICATION-PROTOCOL)% %RESPONSE_CODE% %RESPONSE_CODE_DETAILS% %CONNECTION_TERMINATION_DETAILS% "%UPSTREAM_TRANSPORT_FAILURE_REASON%" %BYTES_RECEIVED% %BYTES_SENT% %DURATION% "%REQ(X-FORWARDED-FOR)%" "%REQ(X-REQUEST-ID)%" %UPSTREAM_CLUSTER% %UPSTREAM_LOCAL_ADDRESS% %DOWNSTREAM_LOCAL_ADDRESS% %DOWNSTREAM_REMOTE_ADDRESS% %ROUTE_NAME%
    configSources:
    - address: k8s://
    - address: xds://meshregistry.mesh-operator.svc:16010
    defaultConfig:
      discoveryAddress: istiod.istio-system.svc:15012
      holdApplicationUntilProxyStarts: true
      proxyMetadata:
        ISTIO_META_DNS_AUTO_ALLOCATE: "true"
        ISTIO_META_DNS_CAPTURE: "true"
      tracing:
        zipkin:
          address: zipkin.istio-system:9411
    enablePrometheusMerge: true
    enableTracing: true
    rootNamespace: istio-system
    trustDomain: cluster.local
  meshNetworks: 'networks: {}'
kind: ConfigMap
```
