### ISSUE TITLE
GlobalSidecar DR 资源支持配置 OutlierDetection 

### ISSUE THREAD

**Issue by Patrick0308** [slime-io/slime#477]
**问题背景**
OutlierDetection 是异常检测配置，在多 region 环境中，我们遇到的问题是开启 locality 负载均衡功能时，如果在 DR 中没有配置 OutlierDetection，那么请求会根据轮训的策略负载到另一个 region 的 global sidecar ，这个不是我们想要期望的。

**您想要的解决方案**
能配置 global sidecar 的 outlier detection 

**您考虑过的替代方案**

**额外的上下文**

**Comment by MouceL** [comment]
meshconfig 中如下设置 似乎可以达到你的目的

```yaml
    serviceSettings:
      - settings:
          clusterLocal: true
        hosts:
          - "global-sidecar.mesh-operatorsvc.cluster.local"
```

可以设置路由至本集群 global-sidecar
