### ISSUE TITLE
关闭自动懒加载后，结果不生效

### ISSUE THREAD

**Issue by palagend** [slime-io/slime#517]
**问题描述**
在SlimeBoot中把autoFence设置为false之后，设置把autoPort和defaultFence都设置为false后，自动创建的ServiceFence资源都不会自动删除，即使手动删除这些资源，又会被自动创建。

**影响的子模块(在下面列表中打'X')**

- [ x] 配置懒加载
- [ ] 插件管理
- [ ] 智能限流
- [ ] 注册仓库
- [x ] 安装Boot

**重现问题的步骤**
1. 修改SlimeBoot资源的配置 `kubectl edit slb -n mesh-operator lazyload`，修改后的内容如下：
```yaml
...
module:
  - enable: true
    general:
      autoFence: false
      autoPort: false                                                                                                                                          
      defaultFence: false                                                                                                                                      
      globalSidecarMode: cluster                                                                                                                             
      metricSourceType: accesslog                                                                                                                              
      wormholePort:                                                                                                                                            
      - "9080"                                                                                                                                                 
    global:                                                                                                                                                    
      log:                                                                                                                                                     
        logLevel: info                                                                                                                                         
      slimeNamespace: mesh-operator                                                                                                                            
    kind: lazyload                                                                                                                                             
    name: lazyload                                                                                                                                             
  namespace: mesh-operator   
...
```
2. 查看bookinfo命名空间的svf资源，`kubectl get svf -n demo`， 输出内容如下：
```bash
kubectl get svf -n demo
NAME          AGE
details       40m
productpage   20h
ratings       20h
reviews       20h


kubectl get svf -oyaml details -n demo
apiVersion: microservice.slime.io/v1alpha1
kind: ServiceFence
metadata:
  creationTimestamp: "2025-03-11T07:26:23Z"
  generation: 1
  labels:
    app.kubernetes.io/created-by: fence-controller
  name: details
  namespace: demo
  resourceVersion: "112446050"
  uid: 827c4be6-9a82-4ff0-bd32-d612c2533684
spec:
  enable: true
  workloadSelector:
    fromService: true
status:
  domains: {}
```
上面的资源依然存在，autoFence设置为false后，好像并没有关掉懒加载。
