### ISSUE TITLE
[Configuration Lazy Loading]: Failed to create SlimeBoot CR

### ISSUE THREAD

**Issue by g0194776** [slime-io/slime#8]
**Bug description**
Failed to create SlimeBoot CR, I just followed the official guides at the main page of Github repository [here](https://github.com/slime-io/slime).

The content I was attempting to create:
```yaml
apiVersion: config.netease.com/v1alpha1
kind: SlimeBoot
metadata:
  name: lazyload
  namespace: mesh-operator
spec:
  module:
    - fence:
        enable: true
        wormholePort:
        - 9080
      name: slime-fence
 component:
   globalSidecar:
     enable: true
     namespace:
       - zhl
   pilot:
     enable: true
     image:
       repository: docker.io/bcxq/pilot
       tag: preview-1.3.7-v0.0.1
   reportServer:
     enable: true
     image:
       repository: docker.io/bcxq/mixer
       tag: preview-1.3.7-v0.0.1
```

Error:
```shell
[root@10 netease]# kubectl create -f slimeboot.yml
error: error parsing slimeboot.yml: error converting YAML to JSON: yaml: line 12: did not find expected key
```

Slimeboot has been deployed successfully.
```shell
[root@10 netease]# kubectl get pods -n mesh-operator
NAME                          READY   STATUS    RESTARTS   AGE
slime-boot-68fd9cd867-brk6z   1/1     Running   0          116m
[root@10 netease]#
```

**Affected sub-moudle (please put an X in all that apply)**

[x] Configuration Lazy Loading
[ ] Http Plugin Management
[ ] Adaptive Ratelimit
[x] Slime Boot

**Steps to reproduce the bug**
